name: main_push

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: code checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
        
      - name: Debug - Check files in the workspace
        run: ls -la

      - name: Build Docker Image
        run: |
          docker build -t test-git-action .

      - name: Push Lastest Image to Docker Hub
        run: |
          docker tag test-git-action:latest dandihara/test-git-action:latest
          docker push dandihara/test-git-action:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo apt update
            sudo apt install -y docker.io
            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/test-git-action:latest
            docker images
            docker stop test-git-action || true
            docker rm test-git-action || true
            docker run -d --name test-git-action -p 80:8000 ${{ secrets.DOCKER_USERNAME }}/test-git-action:latest

      # - name: 가져온 이미지로 컨테이너 실행
      #   run: |
      #     docker run -d --name test-git-action-container -p 8000:8000 dandihara/test-git-action:latest
      #     docker ps
