name: main_push

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: code checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
        
      - name: Debug - Check files in the workspace
        run: ls -la

      - name: Build Docker Image
        run: |
          docker build -t test-git-action .

      - name: Push Lastest Image to Docker Hub
        run: |
          docker tag test-git-action:latest dandihara/test-git-action:latest
          docker push dandihara/test-git-action:latest

      - name: Docker Hub에서 최신화 이미지 가져오기
        run: docker pull dandihara/test-git-action:latest

      - name: 이미지 pulling 정상 작업 확인
        run: docker images

      - name: 가져온 이미지로 컨테이너 실행
        run: |
          docker run -d --name test-git-action-container -p 8000:8000 dandihara/test-git-action:latest
          docker ps
